### ISSUE TITLE
[BUG] Firmware wont compile on python 3.14 because of pillow build errors

### ISSUE THREAD

**Issue by zapotah** [prusa3d/Prusa-Firmware-Buddy#5278]
### Printer model

All

### Firmware version

any

### Printing from...

none

### Describe the bug

python utils/build.py throws errors in bootstrap because pillow fails to build

```
     gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -march=x86-64-v3 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/tmp/pkg/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -fno-semantic-interposition -march=x86-64-v3 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/tmp/pkg/src=/usr/src/debug/python -flto=auto -march=x86-64-v3 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/tmp/pkg/src=/usr/src/debug/python -flto=auto -fPIC -DHAVE_LIBTIFF -DHAVE_LIBJPEG -DHAVE_OPENJPEG -DHAVE_LIBZ -DHAVE_LIBIMAGEQUANT -DHAVE_XCB -DPILLOW_VERSION=\"10.4.0\" -I/usr/include/freetype2 -I/usr/include/openjpeg-2.5 -I/usr/include -I/usr/include/webp -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/fribidi -I/home/zapotah/prusafirmware/Prusa-Firmware-Buddy/.venv/include -I/usr/local/include -I/home/zapotah/prusafirmware/Prusa-Firmware-Buddy/.venv/include -I/usr/include/python3.14 -c src/_imaging.c -o build/temp.linux-x86_64-cpython-314/src/_imaging.o
      src/_webp.c:930:28: error: initialization of ‘PyObject * (*)(PyObject *, PyObject *)’ {aka ‘struct _object * (*)(struct _object *, struct _object *)’} from incompatible pointer type ‘PyObject * (*)(void)’ {aka ‘struct _object * (*)(void)’} [-Wincompatible-pointer-types]
        930 |     {"WebPDecoderVersion", WebPDecoderVersion_wrapper, METH_NOARGS, "WebPVersion"},
            |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
      src/_webp.c:930:28: note: (near initialization for ‘webpMethods[4].ml_meth’)
      src/_webp.c:887:1: note: ‘WebPDecoderVersion_wrapper’ declared here
        887 | WebPDecoderVersion_wrapper() {
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~
      src/_webp.c:932:6: error: initialization of ‘PyObject * (*)(PyObject *, PyObject *)’ {aka ‘struct _object * (*)(struct _object *, struct _object *)’} from incompatible pointer type ‘PyObject * (*)(void)’ {aka ‘struct _object * (*)(void)’} [-Wincompatible-pointer-types]
        932 |      WebPDecoderBuggyAlpha_wrapper,
            |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/_webp.c:932:6: note: (near initialization for ‘webpMethods[5].ml_meth’)
      src/_webp.c:915:1: note: ‘WebPDecoderBuggyAlpha_wrapper’ declared here
        915 | WebPDecoderBuggyAlpha_wrapper() {
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      building 'PIL._imagingtk' extension
      creating build/temp.linux-x86_64-cpython-314/src/Tk
```

### How to reproduce

build with python 3.14

### Expected behavior

firmware builds

**Comment by jandslay** [comment]
I'm not naturally curious, but what are you up to? Here's a little tip: Try updating your Pillow version.

**Comment by zapotah** [comment]
Going to break the appendix on the XL and patch the fan max speeds myself. Cant wait forever for a new release since i have projects waiting where i need to make sure the calibrations are correct and screwing around with the shrouds and heatsink fans is taking way too much time. I have had too many prints fail now due to maintenance throwing off the calibrations and since ive had to start up the XL without one or more tools attached, it invalidates the fan tests and i dont have the time to do workarounds all the time.

I'll try to update pillow in requirements and see if that helps the 3.14 compilation. 3.11 works fine.

**Comment by zapotah** [comment]
pillow 12.2.0 allows for the firmware to compile with 3.14. I need to sleep at this point so I will test flashing the new firmware tomorrow.

**Comment by zapotah** [comment]
Flashed the patched 6.4.1 firmware and it fixes #5265 and i have so far not seen any immediate issues with the printer after ~24h of printing.

**Comment by jandslay** [comment]
Would you like to share it with us?

**Comment by zapotah** [comment]
not stale, please update the pipeline.

**Comment by zapotah** [comment]
tested with 6.4.2 on XL, using pillow 12.2.0 still works fine.

**Comment by zapotah** [comment]
Still needs patching....

**Comment by zapotah** [comment]
Still an issue at 6.10.2 but pillow 12.3.0 seems to work just fine for building the firmware.
